### ISSUE TITLE
Decode example?

### ISSUE THREAD

**Issue by matthewcummings** [guillp/jwskate#10]
This is a great library, just wondering if you could add an example showing how to decode a JWT token.

**Comment by guillp** [comment]
Just pass the JWT value, as a string, to Jwt:
`jwt = Jwt("<your.jwt.here>")`

You can then access headers, claims and all methods as described in the readme.

I'm on a mobile phone right now, so can't elaborate much further, but you may also review the tests for additional examples.

**Comment by matthewcummings** [comment]
OK, thanks. I'm looking for a way to cache the signing key when I decode tokens. Is that possible with your library?

**Comment by guillp** [comment]
What do you mean by caching? If you retrieve the keys from an external endpoint and want to have them locally cached, there is currently nothing in jwskate to help you do that.  But there is probably some other libs that will do it properly anyway 😊

**Comment by guillp** [comment]
see https://github.com/guillp/jwskate/blob/main/docs/recipes.md#parsing-a-jwt .
Closing this, but feel free to comment if you need more explanations
